import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AlertTriangle } from "lucide-react";

export function Disclaimer() {
  return (
    <Alert>
      <AlertTriangle className="h-4 w-4" />
      <AlertTitle>For Educational & Research Purposes Only</AlertTitle>
      <AlertDescription>
        This system is NOT a medical device and does not provide medical advice or diagnosis. All outputs are generated by an AI model and should be considered assistive and non-prescriptive.
      </AlertDescription>
    </Alert>
  );
}
